Port to nan for compatibility with newer V8/Node versions.
This compiles with node 0.10.33 and seems to work in some cursory
tests.

This comes near to compiling with node 0.12.0, except for a bunch of
errors like

- error: ‘DeleteAllSnapshots’ is not a member of ‘v8::HeapProfiler’

- error: ‘class v8::CpuProfileNode’ has no member named ‘GetSelfTime’

These are changes to the V8 profiler API that are not abstracted by
nan.